/* DDL: CREATE , ALTER, DROP, TRUNCATE, USE */

--1: CRIAR UMA DATABASE
--CREATE DATABASE TREINAMENTO_SQL

--2: MUDAR CONTEXTO DA QUERY
USE TREINAMENTO_SQL

--3: CRIAR UM SCHEMA
--CREATE SCHEMA TREINAMENTO

--4: CRIAR UMA TABELA
CREATE TABLE TREINAMENTO.TABELA_01 (
COLUNAS_INTEIRO INT,
COLUNA_TEXTO VARCHAR(20),
COLUNA_MONTETARIO SMALLMONEY,
COLUNA_NUMERICA NUMERIC(5,3)
)

--5: ADICIONAR UMA COLUNA A UMA TABELA JÁ EXISTENTE - 1 COLUNA POR VEZ
ALTER TABLE TREINAMENTO.TABELA_01
ADD COLUNA_DATA1 DATE

--5: ADICIONAR UMA COLUNA A UMA TABELA JÁ EXISTENTE - MAIS DE UMA COLUNA POR VEZ
ALTER TABLE TREINAMENTO.TABELA_01
ADD COLUNA_DATA2 DATE, COLUNA_HORA TIME

--6: ALTERAR O TIPO DE DADOS DE UMA COLUNA EXISTENTE
ALTER TABLE TREINAMENTO.TABELA_01
ALTER COLUMN COLUNAS_INTEIRO BIGINT

-- View padrão do sistema para visualiar metadados da tabela
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TABELA_01'

--7: DROPAR(DELETAR) UMA COLUNA JÁ EXISTENTE NA TABELA
ALTER TABLE TREINAMENTO.TABELA_01
DROP COLUMN COLUNA_DATA2

--8: APAGAR/DELETAR UMA TABELA. OBS SE TIVER REFERENCIA DE CHAVE ESTRANGEIRA, VC NÃO CONSEGUE APAGAR A TABELA
DROP TABLE TREINAMENTO.TABELA_01

--9: TRUNCATE TABLE (APAGAR OS DADOS EXISTENTES)
TRUNCATE TABLE TREINAMENTO.TABELA_01





/*** DML: INSERT, UPDATE, DELETE, MERGE ***/

--1: CRIAR UMA TABELA
CREATE TABLE TREINAMENTO.TABELA_01 (
COLUNA_INTEIRO INT,
COLUNA_TEXTO VARCHAR(20),
COLUNA_MONETARIO SMALLMONEY,
COLUNA_NUMERICA NUMERIC(5,3),
COLUNA_DATA DATE
)

SELECT * FROM treinamento.TABELA_01

--2: INSERT SEM DEFINIR AS COLUNAS - NÃO É MUITO RECOMENDADA!!
INSERT INTO TREINAMENTO.TABELA_01
VALUES (3, 'TEXTO_C', 44.4, 55.5, '2022-07-03')

--3: Insert definidindo as colunas em ordem aleatorio - Lembrar que os valores devem respeitar a ordem das colunas.
INSERT INTO treinamento.TABELA_01 (COLUNA_DATA, COLUNA_TEXTO, COLUNA_INTEIRO, COLUNA_MONETARIO, COLUNA_NUMERICA)
VALUES ('2021-07-03', 'TEXTO_D', 10, 77.8, 98.9)

--4: INSERT DEFININDO APENAS ALGUMAS COLUNAS
INSERT INTO treinamento.TABELA_01 (COLUNA_TEXTO, COLUNA_DATA)
VALUES ('TEXTO_E', '2021-07-03')

--5: INSERT COM VARIOS VALORES - PODE-SE INSERIR LINHAS COM UM UNICO COMANDO INSERT
INSERT INTO treinamento.TABELA_01 (COLUNA_TEXTO, COLUNA_DATA)
VALUES	('TEXTO_F', '2021-07-03'),
		('TEXTO_G', '2021-07-04'),
		('TEXTO_H', '2021-07-05'),
		('TEXTO_I', '2021-07-06')

SELECT * FROM treinamento.TABELA_01
 
-- 6: ATUALIZAR UMA COLUNA ESPECIFICA COM FILTRO. BOA PRATICA: QUANTO MAIS FILTRO MELHOR
UPDATE treinamento.TABELA_01
SET COLUNA_INTEIRO = 54
WHERE COLUNA_TEXTO IN ('TEXTO_E', 'TEXTO_F')
AND COLUNA_DATA = '2021-07-03'

SELECT * FROM treinamento.TABELA_01

-- 7: ATUALIZAR MAIS DE UMA COLUNA COM FILTRO. BOA PRATICA: QUANTO MAIS FILTRO MELHOR
UPDATE treinamento.TABELA_01
SET COLUNA_INTEIRO = 5,
	COLUNA_MONETARIO = 10.55,
	COLUNA_NUMERICA = 4.99
WHERE COLUNA_TEXTO = 'TEXTO_G'

-- 8:DELETAR UM REGISTRO COM FILTRO. BOA PRATICA: QUANTO MAIS FILTRO MELHOR. 
-- SE O REGISTRO NA TABELA A, ESTIVER SENDO REFERENCIADO NA TABELA B, NÃO SERÁ POSSÍVEL A EXCLUSÃO
DELETE FROM TREINAMENTO.TABELA_01
WHERE COLUNA_TEXTO = 'TEXTO_E'
AND COLUNA_INTEIRO = 54
AND COLUNA_DATA = '2021-07-03'

SELECT * FROM treinamento.TABELA_01